name: lidar_processing_03
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - numpy
  - matplotlib
  - pandas
  - gdal
  - pdal
  - scipy
  - tifffile
  - imageio
  - laspy
  - h5py
  - affine
  - tqdm